# 简化的Telemetry配置 - 确保Kiali能看到基本指标
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-metrics
  namespace: istio-demo
spec:
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: ALL_METRICS
      disabled: false
---
# 分布式追踪配置 - 明确配置Jaeger
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-tracing
  namespace: istio-demo
spec:
  tracing:
  - providers:
    - name: jaeger
    customTags:
      service.name:
        literal:
          value: "%{CANONICAL_SERVICE_NAME}.%{CANONICAL_SERVICE_NAMESPACE}"
      service.namespace:
        environment:
          name: POD_NAMESPACE
      service.version:
        literal:
          value: "v1"
---
# 访问日志配置
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default-access-logging
  namespace: istio-demo
spec:
  accessLogging:
  - providers:
    - name: otel 