apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: default
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    # 模拟成功率检查，实际环境中可以替换为Prometheus查询
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      web:
        url: "http://{{ args.service-name }}"
        headers:
        - key: Host
          value: "{{ args.service-name }}"
        jsonPath: "{$.status}"
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-benchmark
  namespace: default
spec:
  args:
  - name: host
  metrics:
  - name: http-requests
    count: 10
    interval: 5s
    successCondition: result < 0.05
    failureLimit: 3
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: load-tester
                image: appropriate/curl
                command: [sh, -c]
                args: ["curl -o /dev/null -s -w %{time_total} {{ args.host }}"]
              restartPolicy: Never
          backoffLimit: 4 