apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.15.173
  share: /Users/shouzhi/techzhi/project/common/kubernetes/nfs/nfs-exports
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3