apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-pv
  storageClassName: "" 