# TechZhi HTTP Client 配置示例
techzhi:
  http-client:
    enabled: true
    client-type: OK_HTTP  # OK_HTTP 或 APACHE_HTTP_CLIENT
    connect-timeout: 10s
    read-timeout: 30s
    write-timeout: 30s
    
    # 连接池配置
    pool:
      max-total: 200
      default-max-per-route: 50
      time-to-live: 5m
      max-idle-time: 1m
      validate-after-inactivity: true
    
    # 代理配置
    proxy:
      enabled: false
      type: HTTP  # HTTP 或 SOCKS
      host: proxy.example.com
      port: 8080
      username: username
      password: password
      non-proxy-hosts: localhost,127.0.0.1
    
    # SSL配置
    ssl:
      verify-hostname: true
      verify-certificate-chain: true
      trust-store-path: classpath:trust.jks
      trust-store-password: password
      trust-store-type: JKS
      key-store-path: classpath:client.p12
      key-store-password: password
      key-store-type: PKCS12
    
    # 重试配置
    retry:
      enabled: true
      max-attempts: 3
      retry-interval: 1s
      backoff-multiplier: 2.0
      max-retry-interval: 10s
    
    # 日志配置
    logging:
      log-requests: false
      log-responses: false
      log-request-body: false
      log-response-body: false
      max-log-body-size: 1024

    # 文件操作配置
    file-operations:
      # 文件上传配置
      upload:
        # 最大文件大小（字节），-1表示无限制
        max-file-size: 104857600  # 100MB
        # 最大请求大小（字节），-1表示无限制
        max-request-size: 209715200  # 200MB
        # 上传缓冲区大小
        buffer-size: 8192
        # 是否启用进度回调
        enable-progress-callback: true
        # 支持的上传文件类型（空表示支持所有类型）
        allowed-extensions: []
        # 禁止的文件类型
        forbidden-extensions: [exe, bat, sh, cmd]
      
      # 文件下载配置
      download:
        # 下载缓冲区大小
        buffer-size: 8192
        # 下载临时目录
        temp-directory: /tmp/http-client-downloads
        # 是否自动创建目录
        auto-create-directories: true
        # 是否启用进度回调
        enable-progress-callback: true
        # 下载超时时间（针对大文件）
        timeout: 300s
        # 是否支持断点续传
        resume-download: false
      
      # 支持的文件类型映射（用于自动检测Content-Type）
      content-type-mapping:
        # 图片类型
        jpg: image/jpeg
        jpeg: image/jpeg
        png: image/png
        gif: image/gif
        bmp: image/bmp
        webp: image/webp
        svg: image/svg+xml
        
        # 文档类型
        pdf: application/pdf
        doc: application/msword
        docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
        xls: application/vnd.ms-excel
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        ppt: application/vnd.ms-powerpoint
        pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
        
        # 文本类型
        txt: text/plain
        csv: text/csv
        xml: application/xml
        json: application/json
        html: text/html
        htm: text/html
        css: text/css
        js: application/javascript
        ts: application/typescript
        
        # 压缩文件类型
        zip: application/zip
        rar: application/x-rar-compressed
        7z: application/x-7z-compressed
        tar: application/x-tar
        gz: application/gzip
        
        # 音视频类型
        mp3: audio/mpeg
        wav: audio/wav
        mp4: video/mp4
        avi: video/x-msvideo
        mov: video/quicktime 