server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: excel-viewer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    com.example.excelviewer: DEBUG
    org.apache.poi: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 